### ISSUE TITLE
Heading tags in pre-formatted block

### ISSUE THREAD

**Issue by codvio** [nicoulaj/idea-markdown#240] opened 2015-08-03 10:13 UTC
We cannot use "#" sign in pre-formatted blocks.

For instance try this:
https://gist.github.com/codvio/b28656a79302c8bc7939

**Comment by vsch** [comment] 2015-08-18 17:34
Not a bug. That is by the spec. Code blocks and fenced code do not have markdown processing done inside them.

**Comment by codvio** [comment] 2015-08-18 18:25
but it process as markdown. That's what i mean. 

![markdown](https://cloud.githubusercontent.com/assets/12461360/9338860/aab644c0-45ef-11e5-8355-2f1a175e8573.png)

**Comment by vsch** [comment] 2015-08-18 18:59
Sorry. Wasn't clear from your comment. Sounded like you wanted it to work. 

Do you have the 'Fenced code blocks' extension option checked in settings/Other Settings/Markdown?

I tried it and it does work, but only with this extension option turned on. Fenced code blocks are an extension to Markdown and is a selectable option.

**Comment by codvio** [comment] 2015-08-18 19:02
I didn't know such a settings. It works now. Thanks.

**Closed** 2016-05-22 11:12 UTC
